---
- name: This playbook shows how to use templates
  hosts: all
  vars_files:
    - users.yml
  tasks:
  - name: Copying motd_template.j2 template
    template:
      src: motd_template.j2
      dest: /etc/motd
      mode: 0644
      owner: root
      group: root

  - name: Copying user template
    template:
      src: users_templates.j2
      dest: /root/users.txt
      mode: 0644
