---
- name: Demonstration for with_items key used for loop
  hosts: node1.example.com
  gather_facts: no
  vars:
    mail_services:
    - postfix
    - dovecot
    run_task: False
  tasks:

  - name: Ensure packages are installed
    package:
      name: "{{ item }}"
      state: latest
    with_items: "{{ mail_services }}"
    when: mail_services is defined

  - name: Ensuring services are running
    service:
      name: "{{ item }}"
      state: started
    with_items: "{{ mail_services }}"
    when: mail_services is defined
